title: Adi Nugroho
description: Network and infrastructure notes
baseurl: ""
url: https://adiynugroho.github.io
permalink: /:year/:month/:day/:title/
markdown: kramdown
highlighter: rouge
theme: null
